name: 'Comment'
description: 'Comment on an Issue or PR given the PR/Issue Number'

inputs:
  pr_number:
    description: 'The number of the PR to comment on'
    required: true
  message:
    description: 'Comment message to post on the PR'
    required: true
  github-token:
    description: 'GitHub token to authenticate API requests'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create Comment on Issue
      uses: actions/github-script@v7
      env:
        PR_NUMBER: ${{ inputs.pr_number }}
        MESSAGE: ${{ inputs.message }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        script: |
          const pr_number = process.env.PR_NUMBER;
          const message = process.env.MESSAGE;
          await github.rest.issues.createComment({
            issue_number: pr_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
