name: 'Comment'
description: 'Comment on an Issue or PR given the PR/Issue Number'

inputs:
  pr_number:
    description: 'The number of the PR to comment on'
    required: true
  message:
    description: 'Comment message to post on the PR'
    required: true
  github-token:
    description: 'GitHub token to authenticate API requests'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create Comment on Issue
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.inputs.pr_number,
            body: context.inputs.message
          });
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
