name: Check Collaborator
description: Fails if the specified user is not a collaborator on the repo
inputs:
  username:
    description: The GitHub username to check
    required: true
runs:
  using: "composite"
  steps:
    - name: Check if user is a collaborator
      # For API Docs, See: https://octokit.github.io/rest.js/v21/
      # github --> maps to an octokit instance in the script
      uses: actions/github-script@v7
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        # https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#check-if-a-user-is-a-repository-collaborator
        script: |
          const username = "${{ inputs.username }}";
          const result = await github.rest.repos.checkCollaborator({ 
            owner: context.repo.owner,
            repo: context.repo.repo,
            username: username
          });
          if (result.status === 204) {
            console.log(`${username} is a collaborator.`);
          } else {
            throw new Error(`${username} is NOT a collaborator.`);
          }