name: Check Collaborator
description: Fails if the specified user is not a collaborator on the repo
inputs:
  username:
    description: The GitHub username to check
    required: true
runs:
  using: "composite"
  steps:
    - name: Check if user is a collaborator
      # For API Docs, See: https://octokit.github.io/rest.js/v21/
      # github --> maps to an octokit instance in the script
      uses: actions/github-script@v7
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        script: |
          const username = "${{ inputs.username }}";
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          try {
            await github.rest.repos.checkCollaborator({ owner, repo, username });
            console.log(`${username} IS a collaborator.`);
          } catch (error) {
            if (error.status === 404) {
              throw new Error(`${username} is NOT a collaborator.`);
            } else {
              throw error;
            }
          }