name: 'Run Command on a Specified PR'
description: 'Runs a command and posts comments on a PR based on workflow progress'
inputs:
  pr_number:
    description: 'The pull request number'
    required: true
  command:
    description: 'The command to execute on the PR'
    required: false
    default: |
      echo "Running command on branch: ${{ steps.get_src_branch.outputs.branch_name }}"
runs:
  using: "composite"
  steps:
    - uses: svij-sc/test-git-actions/.github/actions/assert-is-collaborator@main
      id: assert_collaborator_ran_workflow
      with:
        username: ${{ github.triggering_actor }}
        initiating-pr-number: ${{ github.event.issue.number }}

    - name: Set up workflow URL
      shell: bash
      run: echo "WORKFLOW_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

    - name: Commment workflow started
      uses: 'svij-sc/test-git-actions/.github/actions/comment-on-pr@main'
      with:
        pr_number: ${{ inputs.pr_number }}
        message: "🔄 [Workflow](${{ env.WORKFLOW_URL }}) started."

    - name: Get PRs source branch name
      id: get_src_branch
      uses: 'svij-sc/test-git-actions/.github/actions/get-pr-src-branch@main'
      with:
        pr_number: ${{ inputs.pr_number }}

    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.get_src_branch.outputs.branch_name }}

    - name: Run specified command on the PR branch
      env:
        BRANCH_NAME: ${{ steps.get_src_branch.outputs.branch_name }}
      shell: bash
      run: |
        echo "Running command on branch: ${{ steps.get_src_branch.outputs.branch_name }}"

    - name: Commment workflow succeeded
      uses: 'svij-sc/test-git-actions/.github/actions/comment-on-pr@main'
      with:
        pr_number: ${{ inputs.pr_number }}
        message: "✅ [Workflow](${{ env.WORKFLOW_URL }}) completed successfully!"

    # Failure handling step
    - name: Comment workflow failed
      # If assert_collaborator_ran_workflow step failed we can skip commenting, as that is handled inside that step
      if: failure() && steps.assert_collaborator_ran_workflow.outcome != 'failure'
      uses: 'svij-sc/test-git-actions/.github/actions/comment-on-pr@main'
      with:
        pr_number: ${{ inputs.pr_number }}
        message: "❌ [Workflow](${{ env.WORKFLOW_URL }}) failed. Please check the logs for more details."

