name: debug-dispatch-action

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR to run the workflow on'
        required: true

jobs:
  run-command-and-comment:
    runs-on: ubuntu-latest
    steps:

      # We need to checkout the code first so we can use actions defined on it
      - uses: actions/checkout@v4 
        with:
          ref: main

      - name: Commment workflow started
        uses: ./.github/actions/comment-on-pr
        with:
          pr_number: ${{ inputs.pr_number }}
          message: "🔄 [Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) started."
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PRs source branch name
        id: pr_src_branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = ${{ inputs.pr_number }};
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            const branchName = pr.data.head.ref;
            console.log("Branch name is:", branchName);
            return branchName;

      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr_src_branch.outputs.result }}

      - name: Run some command
        run: |
          echo "Running command on branch: ${{ steps.pr_src_branch.outputs.result }}"
      
      - name: Commment workflow succeeeded
        uses: ./.github/actions/comment-on-pr
        with:
          pr_number: ${{ inputs.pr_number }}
          message: "✅ [Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) completed successfully!"
          github-token: ${{ secrets.GITHUB_TOKEN }}