name: debug-comment-action

on:
    issue_comment:
        types: [created]

jobs:
  run-command-from-comment:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/debug-action') }}
    permissions: # https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment
      contents: 'read'
      issues: 'write'
      pull-requests: 'write'
    runs-on: ubuntu-latest
    env:
      WORKFLOW_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    
    steps:
      - uses: svij-sc/test-git-actions/.github/actions/assert-is-collaborator@main
        with:
          username: ${{ github.event.comment.user.login }}
          initiating-pr-number: ${{ github.event.issue.number }}

      - uses: svij-sc/test-git-actions/.github/workflows/debug-dispatch-action.yml@main
        with:
          pr_number: ${{ github.event.issue.number }}


      # - name: Commment workflow started
      #   uses: ./.github/actions/comment-on-pr
      #   with:
      #     pr_number: ${{ github.event.issue.number }}
      #     message: "🔄 [Workflow](${{ env.WORKFLOW_URL }}) started."

      # - name: Debug
      #   env:
      #     PR_DEBUG_INFO: ${{ toJson(github.event.issue.pull_request)}}
      #   run: |
      #     echo "Debugging..."
      #     echo "pull_request info: $PR_DEBUG_INFO"
      #     echo "workflow_url: ${{ env.WORKFLOW_URL }}"

      # - name: Comment workflow ended
      #   uses: ./.github/actions/comment-on-pr
      #   with:
      #     pr_number: ${{ github.event.issue.number }}
      #     message: "✅ [Workflow](${{ env.WORKFLOW_URL }}) completed successfully!"
      

      # - name: Checkout branch
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.event.issue.pull_request.head.ref }}

      # - name: Run some command
      #   run: |
      #     echo "Running command on branch: ${{ steps.pr_src_branch.outputs.result }}"
      
      # - name: Commment workflow succeeeded
      #   uses: ./.github/actions/comment-on-pr
      #   with:
      #     pr_number: ${{ inputs.pr_number }}
      #     message: "✅ [Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) completed successfully!"
      #     github-token: ${{ secrets.GITHUB_TOKEN }}