name: debug-pr-action

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened


env:
  # Setting environment variables
  owners: ${{ vars.OWNERS }}
  actor: ${{ github.actor }}
  actorid: ${{ github.actor_id }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Debug
        run: |
          echo "Debugging information:"
          echo "$owners"
          echo "$actor"
          echo "$actorid"
