name: debug-dispatch-action

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR to run the workflow on'
        required: true

jobs:
  run-command-and-comment:
    permissions: # https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment
      contents: 'read'
      issues: 'write'
      pull-requests: 'write'
    runs-on: ubuntu-latest
    steps:
      # We need to checkout the code first so we can use actions defined on it
      - uses: actions/checkout@v4 
        with:
          ref: main

      - name: Commment workflow started
        uses: ./.github/actions/comment-on-pr
        with:
          pr_number: ${{ inputs.pr_number }}
          message: "🔄 [Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) started."

      - name: Get PRs source branch name
        id: get_src_branch
        uses: ./.github/actions/get-pr-src-branch
        with:
          pr_number: ${{ inputs.pr_number }}

      - name: Run some command
        env:
          BRANCH_NAME: ${{ steps.get_src_branch.outputs.branch_name }}
        run: |
          echo "Running command on branch: $BRANCH_NAME"
          echo "Running command on branch: ${{ steps.get_src_branch.outputs.branch_name }}"

      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_src_branch.outputs.branch_name }}

      
      - name: Commment workflow succeeeded
        uses: ./.github/actions/comment-on-pr
        with:
          pr_number: ${{ inputs.pr_number }}
          message: "✅ [Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) completed successfully!"
